{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Plateau size:5 5\n",
      "Position:1 2 N\n",
      "Please input directions for rover.LMLMLMLMM\n",
      "1 3 N\n"
     ]
    }
   ],
   "source": [
    "class Plateau():\n",
    "     \n",
    "    \n",
    "    \n",
    "    def __init__(self, height, width, min_height = 0, min_width = 0):        \n",
    "        self.height = height\n",
    "        self.width = width\n",
    "        self.min_height = min_height\n",
    "        self.min_width = min_width\n",
    "                \n",
    "\n",
    "    def check_move_available(self, rover):        \n",
    "        return rover.X > self.width or rover.Y > self.height or rover.X < self.min_width or rover.Y < self.min_height\n",
    "\n",
    "\n",
    "    \n",
    "\n",
    "class MarsRover():\n",
    "    \n",
    "    RIGHT_ROTATE = {\n",
    "        'N':'E',\n",
    "        'E':'S',\n",
    "        'S':'W',\n",
    "        'W':'N'\n",
    "    }\n",
    "\n",
    "    LEFT_ROTATE = {\n",
    "        'N':'W',\n",
    "        'W':'S',\n",
    "        'S':'E',\n",
    "        'E':'N'\n",
    "    }\n",
    "    \n",
    "    \n",
    "\n",
    "    def __init__(self, X, Y, heading, plateau):\n",
    "        self.X = X\n",
    "        self.Y = Y\n",
    "        self.heading = heading\n",
    "        self.plateau = plateau\n",
    "        \n",
    "        \n",
    "    def run_instructions(self, instruction):\n",
    "        if instruction == 'L':\n",
    "            self.rotate_left()\n",
    "        elif instruction == 'R':\n",
    "            self.rotate_right()\n",
    "        elif instruction == 'M':\n",
    "            self.move()\n",
    "    \n",
    "    \n",
    "    def process(self, instructions):\n",
    "        for i in range(len(instructions)):\n",
    "            self.run_instructions(instructions[i])\n",
    "\n",
    "\n",
    "    def rotate_right(self):\n",
    "        self.heading = self.RIGHT_ROTATE[self.heading]\n",
    "                         \n",
    "    \n",
    "    def rotate_left(self):\n",
    "        self.heading = self.LEFT_ROTATE[self.heading]\n",
    "            \n",
    "            \n",
    "    def move(self):\n",
    "                \n",
    "        if self.heading == 'N':\n",
    "            self.Y += 1\n",
    "        elif self.heading == 'E':\n",
    "            self.X += 1\n",
    "        elif self.heading == 'S':\n",
    "            self.Y -= 1    \n",
    "        elif self.heading == 'W':\n",
    "            self.X -= 1\n",
    "            \n",
    "    def __str__(self):        \n",
    "        return str(self.X) + \" \" + str(self.Y) + \" \" + self.heading\n",
    "    \n",
    "    \n",
    "    \n",
    "\n",
    "    \n",
    "        \n",
    "        \n",
    "def main():\n",
    "\n",
    "    plateau_size = input(\"Plateau size:\")\n",
    "    height = int(plateau_size[0])\n",
    "    width = int(plateau_size[2])\n",
    "    plateau = Plateau(height, width)\n",
    "    '''Set plateau'''\n",
    "    \n",
    "    while True:\n",
    "        position = input(\"Position:\")\n",
    "        while True:\n",
    "            X = int(position[0])\n",
    "            Y = int(position[2])\n",
    "            direction = position[4]\n",
    "            rover = MarsRover(X, Y, direction, plateau)\n",
    "            instructions = input(\"Please input directions for rover.\")\n",
    "            rover.process(instructions)\n",
    "            if plateau.check_move_available(rover):\n",
    "                print (\"You cannot move the rover here.\") \n",
    "            else:\n",
    "                print (rover)\n",
    "                break\n",
    "    \n",
    "    \n",
    "\n",
    "if __name__ == '__main__':\n",
    "    \n",
    "    main()\n",
    "            \n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
